import { createApp } from "../../src/index.js";

const app = createApp();

/** [Auto generated by http-native]
 * [http-native optimization] static-fast-path
 * This route is served by the static fast path and avoids generic bridge dispatch.
 */
/** [Auto generated by http-native]
 * [http-native optimization] static-fast-path
 * This route is served by the static fast path and avoids generic bridge dispatch.
 */
app.get("/", (req, res) => {
  res.json({ hello: "world", time: Date.now() });
});

const server = await app.listen({ port: 3000 });
console.log("Server running at " + server.url);
